export default {
    en: {
        TITLE_FENIST_CLOUD: 'FENIST V4I2 LED CONTROLLER',
        TITLE_FENIST_SENSORS: 'SENSORS DATA',
        TITLE_TINYLED_CLOUD: 'Cloud Chart Management on Tinyled.ru',
        TITLE_FENIST_RELAYS: 'Relays control',
        PREFS_TITLE_CLOUD: 'TinyLED cloud connection',
        PREFS_TITLE_HW: 'Controller hardware settings',
        DEVICE_ID: 'UUID of device',
        INVERSE: 'Light level inverse',
        FREQUENCY: 'PWM frequency',
        RELAY1: 'Relay 1',
        RELAY2: 'Relay 2',
        RELAY3: 'Relay 3',
        RELAY4: 'Relay 4',
        SERIAL_NUMBER: 'Serial Number',
        TEMPERATURE: 'Temperature',
        QTY: 'Quantity',
        MIN: 'Minimum',
        MAX: 'Maximum',
        AVG: 'Average',
        FAN_VOLT: 'Fan voltage',
        FAN_RPM: 'Fan RPM'
    },
    ru: {
        TITLE_FENIST_CLOUD: 'FENIST V4I2 LED КОНТРОЛЛЕР',
        TITLE_FENIST_SENSORS: 'ДАННЫЕ ДАТЧИКОВ',
        TITLE_TINYLED_CLOUD: 'Управление графиком в облаке Tinyled.ru',
        TITLE_FENIST_RELAYS: 'Управление реле',
        PREFS_TITLE_CLOUD: 'Подключение к облаку TinylED',
        PREFS_TITLE_HW: 'Настройки периферии контроллера',
        DEVICE_ID: 'Уникальный идентификатор устройства',
        INVERSE: 'Инверсия освещения',
        FREQUENCY: 'Частота ШИМ',
        RELAY1: 'Реле 1',
        RELAY2: 'Реле 2',
        RELAY3: 'Реле 3',
        RELAY4: 'Реле 4',
        SERIAL_NUMBER: 'Серийный номер',
        TEMPERATURE: 'Температура',
        QTY: 'Количество',
        MIN: 'Минимум',
        MAX: 'Максимум',
        AVG: 'Среднее',
        FAN_VOLT: 'Вент. напряжение',
        FAN_RPM: 'Вент. об/мин'
    }
};
