export default {
    en: {
        DISPLAY_TITLE: 'Display',
        THEME: 'Theme',
        LANGUAGE: 'Language',
        THEMES: [
            {text: 'Dark', value: 'dark'},
            {text: 'Light', value: 'light'}
        ],
        AVAILABLE: [
            {text: 'English', value: 'en'},
            {text: 'Русский', value: 'ru'}
        ],
        SUBMIT: 'Submit',
        RESET: 'Reset',
        DEFAULT: 'Default',
        NAME: 'Name',
        PASSWORD: 'Password',
        ACCESS_POINT: 'Access point',
        INTERNET_CONNECTION: 'Internet connection',
        DASHBOARD: 'Dashboard',
        SETTINGS: 'Settings',
        DATE_TIME: 'Date and time',
        CURRENT: 'Current',
        CURRENT_TIME: 'Time',
        NTP_SYNC: 'Synchronize with the Internet',
        IP: 'ip',
        INTERNET: 'Internet',
        DISCONNECTED: 'Disconnected',
        CONNECTED: 'Connected',
        CONFIG_HELPER_HELLO: '<h2>Hello!</h2><br><p> I\'m ThingJS<span class="cpr"></span>. Let me help you with the settings. A few simple steps and I will be ready to use. You can:</p> <ul><li>Control me from any device that supports a WEB browser;</li><li>Control me from anywhere in the world;</li><li>Install applications turning me into different devices</li><li>And much more...</li></ul><br><br><h2>Are you ready?</h2>',
        INTRODUCTION: 'Introduction',
        CONTINUE: 'Continue',
        BACK: 'Back',
        CANCEL: 'Cancel',
        NETWORK: 'Network',
        BEGIN_WORK: 'Completed',
        READY: 'Ready',
        CONFIG_HELPER_READY: '<h2>Great work!</h2><br><p>Now I\'m ready. You can always go back to the settings in the "Settings" section. There you can ask again to help you;) <br><br><h2>Начнем?</h2><br>',
        PASSWORD_NO_CHANGE: 'Password [NO CHANGED]',
        ERROR_AP_NAME: 'Name of SSID is required and at least 6 characters',
        TIME_ZONE: 'Time zone',
        FIRMWARE: 'Firmware',
        NO_CONNECT: '[NO CONNECT]',
        CLOSE: 'Close',
        NETWORK_ERROR: 'Network error. Please check your connection and try again.',
        STATE_ERROR: 'Error of loading state file',
        ERROR_LOAD_APP: 'Error of loading application',
        APPS_TITLE: 'Applications',
        APPLICATION: 'Application',
        VENDOR: 'Vendor',
        UNINSTALL: 'Uninstall',
        UNINSTALL_APP_TITLE: 'Uninstalling application',
        UNINSTALL_APP_BODY: 'Are you sure you want to uninstall application?',
        INSTALL_NEW_APP: 'Install new application',
        INSTALL_APP_TITLE: 'Install application',
        INSTALL: 'Install',
        DO_SELECT_APP: 'Drag the application file here or click here to select.',
        DESCRIPTION: 'Description',
        SIZE: 'Size',
        ERROR_APP_BUNDLE_FORMAT: 'The file is not an application file or is incompatible',
        ERROR_APP_INSTALL: 'Error of install application',
        INFO_APP_ALREADY_INSTALLED: 'Application is already installed. If you continue, the application will be updated. Found version: ',
        VERSION: 'Version',
        ERROR_APP_UNINSTALL: 'Error of uninstall application',
        ERROR_FIRMWARE: 'Error of flashing firmware',
        UPDATE_FIRMWARE_TITLE: 'Update firmware',
        DO_FIRMWARE: 'FLASHING',
        DETECTED_DEBUGGER_REQUEST: 'Detected debugger request from [%appname%] <br><a href="%url%" target="_blank">Start debugger.</a>',
        DEBUGGER: 'DEBUGGER'
    },
    ru: {
        DISPLAY_TITLE: 'Экран',
        THEME: 'Тема',
        LANGUAGE: 'Язык',
        THEMES: [
            {text: 'Темная', value: 'dark'},
            {text: 'Светлая', value: 'light'}
        ],
        AVAILABLE: [
            {text: 'English', value: 'en'},
            {text: 'Русский', value: 'ru'}
        ],
        SUBMIT: 'Применить',
        RESET: 'Сброс',
        DEFAULT: 'По умолчанию',
        NAME: 'Наименование',
        PASSWORD: 'Пароль',
        ACCESS_POINT: 'Точка доступа',
        INTERNET_CONNECTION: 'Соединение с Интернет',
        DASHBOARD: 'Рабочий стол',
        SETTINGS: 'Настройки',
        DATE_TIME: 'Дата и время',
        CURRENT: 'Текущее',
        CURRENT_TIME: 'Время',
        NTP_SYNC: 'Синхронизировать с Интернет',
        IP: 'ip',
        INTERNET: 'Интернет',
        DISCONNECTED: 'Нет соединения',
        CONNECTED: 'Подключено',
        CONFIG_HELPER_HELLO: '<h2>Привет!</h2><br><p>Я ThingJS<span class="cpr"></span>. Позволь помочь тебе с настройками. Несколько простых шагов и я буду готов к использованию. Ты сможешь:</p> <ul><li>Управлять мной c любого устройства, поддерживающего браузер;</li><li>Управлять мной из любой точки мира;</li><li>Устанавливать приложения превращая меня в различные устройства;</li><ul>И многое другое...</ul></ul><br><br><h2>Начнем?</h2>',
        INTRODUCTION: 'Знакомство',
        CONTINUE: 'Далее',
        BACK: 'Назад',
        CANCEL: 'Отмена',
        NETWORK: 'Сеть',
        BEGIN_WORK: 'Начало работы',
        READY: 'Готово',
        CONFIG_HELPER_READY: '<h2>Отличная работа!</h2><br><p>Теперь я готов. Ты всегда сможешь вернуться к настройкам в разделе "Настройки". Там же ты сможешь вновь попросить помочь тебе меня;) <br><br><h2>Начнем?</h2><br>',
        PASSWORD_NO_CHANGE: 'Пароль [БЕЗ ИЗМЕНЕНИЙ]',
        ERROR_AP_NAME: 'Не менее 6 символов латиницей',
        TIME_ZONE: 'Часовой пояс',
        FIRMWARE: 'Версия системы',
        NO_CONNECT: '[НЕ ПОДКЛЮЧАТЬ]',
        CLOSE: 'Закрыть',
        NETWORK_ERROR: 'Ошибка сети. Проверьте подключение и повторите попытку.',
        STATE_ERROR: 'Ошибка чтения статуса контроллера',
        ERROR_LOAD_APP: 'Ошибка загрузки приложения',
        APPS_TITLE: 'Приложения',
        APPLICATION: 'Приложение',
        VENDOR: 'Поставщик',
        UNINSTALL: 'Удалить',
        UNINSTALL_APP_TITLE: 'Удаление приложения',
        UNINSTALL_APP_BODY: 'Вы уверены, что хотите удалить приложение?',
        INSTALL_NEW_APP: 'Установить новое приложение',
        INSTALL_APP_TITLE: 'Установка приложения',
        INSTALL: 'Установить',
        DO_SELECT_APP: 'Перетащите сюда файл приложения или кликните здесь для выбора.',
        DESCRIPTION: 'Описание',
        SIZE: 'Размер',
        ERROR_APP_BUNDLE_FORMAT: 'Файл не является файлом приложения или несовместим',
        ERROR_APP_INSTALL: 'Ошибка установки приложения',
        INFO_APP_ALREADY_INSTALLED: 'Приложение уже установлено. Если вы продолжите, приложение будет обновлено. Установлена версия: ',
        VERSION: 'Версия',
        ERROR_APP_UNINSTALL: 'Ошибка удаления приложения!',
        ERROR_FIRMWARE: 'Ошибка прошивки контроллера',
        UPDATE_FIRMWARE_TITLE: 'Обновление прошивки',
        DO_FIRMWARE: 'Обновить',
        DETECTED_DEBUGGER_REQUEST: 'Обнаружен запрос на отладку [%appname%] <br> <a href="%url%" target="_blank">Запустить отладчик.</a>',
        DEBUGGER: 'DEBUGGER'
    }
};
